// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "filter", "symbols": ["brand"]},
    {"name": "filter", "symbols": ["carname"]},
    {"name": "filter", "symbols": ["vehicletype"]},
    {"name": "filter", "symbols": ["fueltype"]},
    {"name": "filter", "symbols": ["brand", "andOR", "carname"]},
    {"name": "filter", "symbols": ["carname", "andOR", "brand"]},
    {"name": "filter", "symbols": ["carname", "andOR", "vehicletype"]},
    {"name": "filter", "symbols": ["vehicletype", "andOR", "carname"]},
    {"name": "filter", "symbols": ["vehicletype", "andOR", "fueltype"]},
    {"name": "filter", "symbols": ["fueltype", "andOR", "vehicletype"]},
    {"name": "filter", "symbols": ["fueltype", "andOR", "carname"]},
    {"name": "filter", "symbols": ["carname", "andOR", "fueltype"]},
    {"name": "filter", "symbols": ["brand", "andOR", "carname", "andOR", "vehicletype"]},
    {"name": "filter", "symbols": ["brand", "andOR", "vehicletype", "andOR", "carname"]},
    {"name": "filter", "symbols": ["carname", "andOR", "brand", "andOR", "vehicletype"]},
    {"name": "filter", "symbols": ["carname", "andOR", "vehicletype", "andOR", "brand"]},
    {"name": "filter", "symbols": ["vehicletype", "andOR", "brand", "andOR", "carname"]},
    {"name": "filter", "symbols": ["vehicletype", "andOR", "carname", "andOR", "brand"]},
    {"name": "filter", "symbols": ["carname", "andOR", "vehicletype", "andOR", "fueltype"]},
    {"name": "filter", "symbols": ["carname", "andOR", "fueltype", "andOR", "vehicletype"]},
    {"name": "filter", "symbols": ["vehicletype", "andOR", "carname", "andOR", "fueltype"]},
    {"name": "filter", "symbols": ["vehicletype", "andOR", "fueltype", "andOR", "carname"]},
    {"name": "filter", "symbols": ["fueltype", "andOR", "carname", "andOR", "vehicletype"]},
    {"name": "filter", "symbols": ["fueltype", "andOR", "vehicletype", "andOR", "carname"]},
    {"name": "filter", "symbols": ["vehicletype", "andOR", "fueltype", "andOR", "brand"]},
    {"name": "filter", "symbols": ["vehicletype", "andOR", "brand", "andOR", "fueltype"]},
    {"name": "filter", "symbols": ["fueltype", "andOR", "vehicletype", "andOR", "brand"]},
    {"name": "filter", "symbols": ["fueltype", "andOR", "brand", "andOR", "vehicletype"]},
    {"name": "filter", "symbols": ["brand", "andOR", "vehicletype", "andOR", "fueltype"]},
    {"name": "filter", "symbols": ["brand", "andOR", "fueltype", "andOR", "vehicletype"]},
    {"name": "filter", "symbols": ["brand", "andOR", "carname", "andOR", "vehicletype", "andOR", "fueltype"]},
    {"name": "filter", "symbols": ["brand", "andOR", "carname", "andOR", "fueltype", "andOR", "vehicletype"]},
    {"name": "filter", "symbols": ["brand", "andOR", "vehicletype", "andOR", "carname", "andOR", "fueltype"]},
    {"name": "filter", "symbols": ["brand", "andOR", "vehicletype", "andOR", "fueltype", "andOR", "carname"]},
    {"name": "filter", "symbols": ["brand", "andOR", "fueltype", "andOR", "carname", "andOR", "vehicletype"]},
    {"name": "filter", "symbols": ["brand", "andOR", "fueltype", "andOR", "vehicletype", "andOR", "carname"]},
    {"name": "filter", "symbols": ["carname", "andOR", "brand", "andOR", "vehicletype", "andOR", "fueltype"]},
    {"name": "filter", "symbols": ["carname", "andOR", "brand", "andOR", "fueltype", "andOR", "vehicletype"]},
    {"name": "filter", "symbols": ["carname", "andOR", "vehicletype", "andOR", "brand", "andOR", "fueltype"]},
    {"name": "filter", "symbols": ["carname", "andOR", "vehicletype", "andOR", "fueltype", "andOR", "brand"]},
    {"name": "filter", "symbols": ["carname", "andOR", "fueltype", "andOR", "brand", "andOR", "vehicletype"]},
    {"name": "filter", "symbols": ["carname", "andOR", "fueltype", "andOR", "vehicletype", "andOR", "brand"]},
    {"name": "filter", "symbols": ["vehicletype", "andOR", "brand", "andOR", "carname", "andOR", "fueltype"]},
    {"name": "filter", "symbols": ["vehicletype", "andOR", "brand", "andOR", "fueltype", "andOR", "carname"]},
    {"name": "filter", "symbols": ["vehicletype", "andOR", "carname", "andOR", "brand", "andOR", "fueltype"]},
    {"name": "filter", "symbols": ["vehicletype", "andOR", "carname", "andOR", "fueltype", "andOR", "brand"]},
    {"name": "filter", "symbols": ["vehicletype", "andOR", "fueltype", "andOR", "brand", "andOR", "carname"]},
    {"name": "filter", "symbols": ["vehicletype", "andOR", "fueltype", "andOR", "carname", "andOR", "brand"]},
    {"name": "filter", "symbols": ["fueltype", "andOR", "brand", "andOR", "carname", "andOR", "vehicletype"]},
    {"name": "filter", "symbols": ["fueltype", "andOR", "brand", "andOR", "vehicletype", "andOR", "carname"]},
    {"name": "filter", "symbols": ["fueltype", "andOR", "carname", "andOR", "brand", "andOR", "vehicletype"]},
    {"name": "filter", "symbols": ["fueltype", "andOR", "carname", "andOR", "vehicletype", "andOR", "brand"]},
    {"name": "filter", "symbols": ["fueltype", "andOR", "vehicletype", "andOR", "brand", "andOR", "carname"]},
    {"name": "filter", "symbols": ["fueltype", "andOR", "vehicletype", "andOR", "carname", "andOR", "brand"]},
    {"name": "brand$string$1", "symbols": [{"literal":"B"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "brand", "symbols": ["brand$string$1", "equals", "string"]},
    {"name": "brand$string$2", "symbols": [{"literal":"b"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "brand", "symbols": ["brand$string$2", "equals", "string"]},
    {"name": "carname$string$1", "symbols": [{"literal":"N"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "carname", "symbols": ["carname$string$1", "equals", "string"]},
    {"name": "carname$string$2", "symbols": [{"literal":"n"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "carname", "symbols": ["carname$string$2", "equals", "string"]},
    {"name": "vehicletype$string$1", "symbols": [{"literal":"V"}, {"literal":"e"}, {"literal":"h"}, {"literal":"i"}, {"literal":"c"}, {"literal":"l"}, {"literal":"e"}, {"literal":"T"}, {"literal":"y"}, {"literal":"p"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "vehicletype", "symbols": ["vehicletype$string$1", "equals", "string"]},
    {"name": "vehicletype$string$2", "symbols": [{"literal":"v"}, {"literal":"e"}, {"literal":"h"}, {"literal":"i"}, {"literal":"c"}, {"literal":"l"}, {"literal":"e"}, {"literal":"t"}, {"literal":"y"}, {"literal":"p"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "vehicletype", "symbols": ["vehicletype$string$2", "equals", "string"]},
    {"name": "fueltype$string$1", "symbols": [{"literal":"F"}, {"literal":"u"}, {"literal":"e"}, {"literal":"l"}, {"literal":"T"}, {"literal":"y"}, {"literal":"p"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "fueltype", "symbols": ["fueltype$string$1", "equals", "string"]},
    {"name": "fueltype$string$2", "symbols": [{"literal":"f"}, {"literal":"u"}, {"literal":"e"}, {"literal":"l"}, {"literal":"t"}, {"literal":"y"}, {"literal":"p"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "fueltype", "symbols": ["fueltype$string$2", "equals", "string"]},
    {"name": "andOR", "symbols": ["and"]},
    {"name": "andOR", "symbols": ["or"]},
    {"name": "equals$string$1", "symbols": [{"literal":" "}, {"literal":"="}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "equals", "symbols": ["equals$string$1"]},
    {"name": "and$string$1", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "and", "symbols": ["and$string$1"]},
    {"name": "or$string$1", "symbols": [{"literal":" "}, {"literal":"o"}, {"literal":"r"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "or", "symbols": ["or$string$1"]},
    {"name": "string", "symbols": [{"literal":"\""}, "characters", {"literal":"\""}]},
    {"name": "characters", "symbols": ["character"]},
    {"name": "characters", "symbols": ["character", "characters"]},
    {"name": "character", "symbols": [/[^\"]/]}
]
  , ParserStart: "filter"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
